# Generated by Django 3.2.13 on 2025-10-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='公開'),
        ),
    ]
