# Generated by Django 3.2.13 on 2025-11-03 05:36

import base.models.item_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_item_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default=base.models.item_models.create_id, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
